import os

DATA_PATH = "Dataset/actualdataset/AAPL.csv"
OUTPUT_DIR = "output"

DATE_COLUMN = "Date"
TARGET_COLUMN = "Close"

SEQUENCE_LENGTH = int(os.getenv("LSTM_SEQUENCE_LENGTH", 60))
TRAIN_SPLIT = 0.8
NORMALIZE_RANGE = (0, 1)

LSTM_UNITS = 64
LSTM_LAYERS = 2
DROPOUT_RATE = 0.2
DENSE_UNITS = 32
LEARNING_RATE = float(os.getenv("LSTM_LEARNING_RATE", 0.001))

BATCH_SIZE = 32
EPOCHS = int(os.getenv("LSTM_EPOCHS", 100))
VALIDATION_SPLIT = 0.1
EARLY_STOPPING_PATIENCE = 10
EARLY_STOPPING_MONITOR = "val_loss"

RAW_PLOT_FILE = "raw_price.png"
PREDICTION_PLOT_FILE = "AAPL_prediction.png"
CANDLESTICK_PLOT_FILE = "candlestick.png"
RESIDUAL_PLOT_FILE = "residuals.png"
PREDICTION_BANDS_PLOT_FILE = "AAPL_prediction_with_bands.png"
CORRELATION_HEATMAP_FILE = "correlation_heatmap.png"
PLOT_DPI = 100
PLOT_FIGSIZE = (12, 6)

MODEL_FILE = "best_model.h5"
TRAINING_SIDECAR_FILE = "training_history.json"
METRICS_FILE = "metrics.json"
RMSE_TARGET = 5.0
MAPE_TARGET = 5.0
AUTONOMOUS_FAILURE_ENV = "LSTM_FORCE_AUTONOMOUS_FAILURE"
AUTONOMOUS_REQUIRED_ARTIFACTS = (MODEL_FILE, METRICS_FILE, PREDICTION_PLOT_FILE)
AUTONOMOUS_ALLOWED_REPAIR_SCOPE = (
    "offline-only",
    "AAPL-only",
    "Close-only",
    "stacked-LSTM",
)
AUTONOMOUS_PASS_STREAK = 3
AUTONOMOUS_MAX_REPAIR_ATTEMPTS = 2
AUTONOMOUS_MAX_REPAIR_MINUTES = 10
REPAIR_LOG_FILE = "REPAIR-LOG.md"

RANDOM_SEED = 42
